#yet another markup languag

name: CI


on:
  push:
    branches: 
        - main
        - any-feature-branch



jobs:
    
    job1:
        runs-on: ubuntu-latest # can even have macos-latest or windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7  # v7 is the version of the action we're using, not the branch of the code; https://github.com/actions/checkout 
        # purpose of checkout code is to get the code from the repository, and put it in the runner machine
            - name: Set up Python
              uses: actions/setup-python@v7  # https://github.com/actions/setup-python
              with:
                python-version: '3.12'  # Specify the Python version you want to use

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt  # Install dependencies from requirements.txt
            - name: Run tests
              run: |
                    pytest
    
    job2: 
        needs: job1  # This job will run after job1 completes successfully  [lint, test-unit]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7  # v7 is the version of the action we're using, not the branch of the code;
            - name: Login to DockerHub
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker image
              uses: docker/build-push-action@v7 #https://github.com/docker/build-push-action
              with:
                push: true
                tags: shivam13juna/oct7_2026_live_ci:latest  # Replace with your Docker Hub username and image name
      